/*
 * To change this license header, choose License Headers in Project Properties.
 * To change this template file, choose Tools | Templates
 * and open the template in the editor.
 */
package quiz.app.java;

import java.awt.Color;
import java.awt.Font;
import java.sql.Connection;
import java.sql.DriverManager;
import java.sql.PreparedStatement;
import java.sql.ResultSet;
import java.sql.Statement;
import javax.swing.BorderFactory;
import javax.swing.SwingConstants;
import javax.swing.border.Border;
import javax.swing.table.DefaultTableCellRenderer;
import javax.swing.table.DefaultTableModel;
import static quiz.app.java.Login.username;

/**
 *
 * @author jasse
 */
public class leaderBoardAdmin extends javax.swing.JFrame {
    DefaultTableModel model;
    Border DeleteBorder = BorderFactory.createLineBorder(Color.RED, 1);

    /**
     * Creates new form leaderBoard
     */
    public leaderBoardAdmin() {
        initComponents();
        updateScoreTable();
        customizeTableHeader();
        fetchAndDisplayData();
        jButton1.setBorder(DeleteBorder);
        jButton1.setVisible(false);
        jLabel6.setVisible(false);
    }

    /**
     * This method is called from within the constructor to initialize the form.
     * WARNING: Do NOT modify this code. The content of this method is always
     * regenerated by the Form Editor.
     */
    @SuppressWarnings("")
    // <editor-fold defaultstate="collapsed" desc="Generated Code">//GEN-BEGIN:initComponents
    private void initComponents() {

        jLabel3 = new javax.swing.JLabel();
        jButton2 = new javax.swing.JButton();
        jLabel6 = new javax.swing.JLabel();
        jButton1 = new javax.swing.JButton();
        jLabel5 = new javax.swing.JLabel();
        jLabel1 = new javax.swing.JLabel();
        jScrollPane1 = new javax.swing.JScrollPane();
        jTable1 = new javax.swing.JTable();
        jLabel2 = new javax.swing.JLabel();

        setDefaultCloseOperation(javax.swing.WindowConstants.EXIT_ON_CLOSE);
        setMinimumSize(new java.awt.Dimension(1280, 768));
        getContentPane().setLayout(null);

        jLabel3.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/app/java/logout.png"))); // NOI18N
        jLabel3.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel3.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel3MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel3);
        jLabel3.setBounds(60, 40, 30, 50);

        jButton2.setBackground(new java.awt.Color(255, 255, 255));
        jButton2.setFont(new java.awt.Font("Tahoma", 1, 18)); // NOI18N
        jButton2.setText("     Log Out");
        jButton2.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton2.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton2ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton2);
        jButton2.setBounds(40, 40, 170, 50);

        jLabel6.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/app/java/delete.png"))); // NOI18N
        jLabel6.setText("jLabel6");
        jLabel6.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel6.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel6MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel6);
        jLabel6.setBounds(1070, 660, 30, 50);

        jButton1.setBackground(new java.awt.Color(255, 255, 255));
        jButton1.setFont(new java.awt.Font("Tahoma", 1, 24)); // NOI18N
        jButton1.setForeground(new java.awt.Color(255, 51, 51));
        jButton1.setText("      DELETE");
        jButton1.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jButton1.addActionListener(new java.awt.event.ActionListener() {
            public void actionPerformed(java.awt.event.ActionEvent evt) {
                jButton1ActionPerformed(evt);
            }
        });
        getContentPane().add(jButton1);
        jButton1.setBounds(1050, 660, 180, 50);

        jLabel5.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/app/java/edit.png"))); // NOI18N
        jLabel5.setText("jLabel3");
        jLabel5.setCursor(new java.awt.Cursor(java.awt.Cursor.HAND_CURSOR));
        jLabel5.addMouseListener(new java.awt.event.MouseAdapter() {
            public void mouseClicked(java.awt.event.MouseEvent evt) {
                jLabel5MouseClicked(evt);
            }
        });
        getContentPane().add(jLabel5);
        jLabel5.setBounds(990, 100, 50, 60);

        jLabel1.setBackground(new java.awt.Color(102, 102, 102));
        jLabel1.setFont(new java.awt.Font("Tahoma", 1, 48)); // NOI18N
        jLabel1.setForeground(new java.awt.Color(51, 51, 51));
        jLabel1.setText("~ LEADERBOARD ~");
        jLabel1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel1);
        jLabel1.setBounds(400, 50, 500, 58);

        jTable1.setFont(new java.awt.Font("Tahoma", 0, 18)); // NOI18N
        jTable1.setModel(new javax.swing.table.DefaultTableModel(
            new Object [][] {

            },
            new String [] {
                "USERNAME", "SCORE"
            }
        ) {
            Class[] types = new Class [] {
                java.lang.String.class, java.lang.Integer.class
            };
            boolean[] canEdit = new boolean [] {
                false, false
            };

            public Class getColumnClass(int columnIndex) {
                return types [columnIndex];
            }

            public boolean isCellEditable(int rowIndex, int columnIndex) {
                return canEdit [columnIndex];
            }
        });
        jTable1.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        jTable1.setFocusable(false);
        jTable1.setGridColor(new java.awt.Color(102, 102, 102));
        jTable1.setRowHeight(50);
        jTable1.setRowMargin(0);
        jTable1.setSelectionBackground(new java.awt.Color(255, 0, 0));
        jTable1.setShowHorizontalLines(false);
        jTable1.getTableHeader().setReorderingAllowed(false);
        jScrollPane1.setViewportView(jTable1);
        if (jTable1.getColumnModel().getColumnCount() > 0) {
            jTable1.getColumnModel().getColumn(0).setResizable(false);
            jTable1.getColumnModel().getColumn(1).setResizable(false);
        }

        getContentPane().add(jScrollPane1);
        jScrollPane1.setBounds(260, 150, 740, 580);

        jLabel2.setIcon(new javax.swing.ImageIcon(getClass().getResource("/quiz/app/java/bgRotatedOpacity035.png"))); // NOI18N
        jLabel2.setText("jLabel2");
        jLabel2.setCursor(new java.awt.Cursor(java.awt.Cursor.CROSSHAIR_CURSOR));
        getContentPane().add(jLabel2);
        jLabel2.setBounds(0, 0, 1280, 770);

        pack();
    }// </editor-fold>//GEN-END:initComponents

    private void jButton1ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton1ActionPerformed
            deleteRows();
    }//GEN-LAST:event_jButton1ActionPerformed

    private void jLabel5MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel5MouseClicked
        jButton1.setVisible(true);
        jLabel6.setVisible(true);
    }//GEN-LAST:event_jLabel5MouseClicked

    private void jButton2ActionPerformed(java.awt.event.ActionEvent evt) {//GEN-FIRST:event_jButton2ActionPerformed
        Login x = new Login();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
        x.getContentPane().setBackground(Color.WHITE);
        this.setVisible(false);
    }//GEN-LAST:event_jButton2ActionPerformed

    private void jLabel6MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel6MouseClicked
         deleteRows();
    }//GEN-LAST:event_jLabel6MouseClicked

    private void jLabel3MouseClicked(java.awt.event.MouseEvent evt) {//GEN-FIRST:event_jLabel3MouseClicked
        Login x = new Login();
        x.setLocationRelativeTo(null);
        x.setVisible(true);
        x.getContentPane().setBackground(Color.WHITE);
        this.setVisible(false);
    }//GEN-LAST:event_jLabel3MouseClicked

    /**
     * @param args the command line arguments
     */
        
    private void customizeTableHeader() {
        jTable1.getTableHeader().setFont(new Font("Segoe UI", Font.BOLD, 30));
        jTable1.getTableHeader().setOpaque(false);
        jTable1.getTableHeader().setBackground(new Color(255,204,0));
        jTable1.getTableHeader().setForeground(Color.BLACK);

        DefaultTableCellRenderer centerRenderer = new DefaultTableCellRenderer();
        centerRenderer.setHorizontalAlignment(SwingConstants.CENTER);
        jTable1.setDefaultRenderer(String.class, centerRenderer);
        jTable1.setDefaultRenderer(Integer.class, centerRenderer);
}
    
      private void updateScoreTable() {
     model = (DefaultTableModel) jTable1.getModel();
    
    String requete = "UPDATE users SET Score = '"+Home.getScore()+"' WHERE userName = '"+username+"'";

    try {
            Class.forName("com.mysql.jdbc.Driver");  
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/quiz-app-java", "root", "admin");
        Statement st = con.createStatement();
            st.executeUpdate(requete);
        
    } catch (Exception e) {
        System.out.println("error d'afficher");
    }
             
    }

     private void fetchAndDisplayData() {
     model = (DefaultTableModel) jTable1.getModel();
    
    String requete = "SELECT userName, Score FROM users ORDER BY Score DESC";

    try {
            Class.forName("com.mysql.jdbc.Driver");  
        Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/quiz-app-java", "root", "admin");
        Statement st = con.createStatement();
        ResultSet res = st.executeQuery(requete);

         while (res.next()) {
            String userName = res.getString("userName");
            int score = res.getInt("Score");
            model.addRow(new Object[]{userName, score});
        }

    } catch (Exception e) {
        System.out.println("error d'afficher");
    }
             
    }

     private void deleteRows() {
        int selectedRow = jTable1.getSelectedRow();

        if (selectedRow == -1) {
            // No row selected, show a message or handle accordingly
            return;
        }

        String selectedUsername = (String) model.getValueAt(selectedRow, 0);

        if (selectedUsername == null || selectedUsername.isEmpty()) {
            System.out.println("Invalid username for deletion.");
            return;
        }

        String deleteQuery = "DELETE FROM users WHERE userName = ?";

        try (
            Connection con = DriverManager.getConnection(
                "jdbc:mysql://localhost:3306/quiz-app-java?useSSL=false", "root", "admin");
             PreparedStatement st = con.prepareStatement(deleteQuery)) {

            st.setString(1, selectedUsername);
            int rowsAffected = st.executeUpdate();

            if (rowsAffected > 0) {
                // Delete successful
                model.removeRow(selectedRow);
            } else {
                System.out.println("Failed to delete user: " + selectedUsername);
            }

        } catch (Exception e) {
            e.printStackTrace();
            System.out.println("Error during deletion");
        }
    }
 public static void main(String args[]) {
        /* Set the Nimbus look and feel */
        //<editor-fold defaultstate="collapsed" desc=" Look and feel setting code (optional) ">
        /* If Nimbus (introduced in Java SE 6) is not available, stay with the default look and feel.
         * For details see http://download.oracle.com/javase/tutorial/uiswing/lookandfeel/plaf.html 
         */
       
        //</editor-fold>
         java.awt.EventQueue.invokeLater(new Runnable() {
            public void run() {
              leaderBoardAdmin x = new leaderBoardAdmin();
              x.setLocationRelativeTo(null);
              x.setVisible(true);
              
            }
        });
    }

    // Variables declaration - do not modify//GEN-BEGIN:variables
    private javax.swing.JButton jButton1;
    private javax.swing.JButton jButton2;
    private javax.swing.JLabel jLabel1;
    private javax.swing.JLabel jLabel2;
    private javax.swing.JLabel jLabel3;
    private javax.swing.JLabel jLabel5;
    private javax.swing.JLabel jLabel6;
    private javax.swing.JScrollPane jScrollPane1;
    private javax.swing.JTable jTable1;
    // End of variables declaration//GEN-END:variables
}
